### ISSUE TITLE
HU10 - Agregar receta

### ISSUE THREAD

**Issue by FlorenciaItati** [Uriel-98/Avocado-ISPC#11]
Como usuario de Avocado quiero poder agregar recetas para tenerlas organizadas y poder compartirlas con otros usuarios.

**_Criterios de aceptación:_**

- La opción de “Agregar receta” debe aparecer en la pantalla de inicio (feed).
- La vista de “agregar receta” es un formulario.
- Permitir a los usuarios cargar imágenes de las recetas.
- Proporcionar campos para ingresar el título de la receta, una descripción breve y cualquier otra información relevante como: tiempo de cocción, nivel de dificultad.
- Debe tener campos específicos para ingresar los ingredientes. (Debe ser un input donde se escriba el ingrediente, que luego se agrega a un contenedor abajo tipo lista). 
- Cada ingrediente agregado tiene un botón “x” para eliminarlo.
- Poder agregar los pasos de preparación (text area).
- Ofrecer la posibilidad de añadir etiquetas o categorías a la receta.
- Debe tener un botón de “Guardar nueva receta”, que guardará la receta con un mensaje de confirmación que diga “Ñam, nueva receta creada!”, y te redirige al feed.
- Debe tener un botón de “Cancelar”, que cancelará la creación de la receta y redirigirá al feed.

**Comment by Loreaylen** [comment]
Categorías posibles:
- Desayuno
- Almuerzo
- Cena
- Entradas
- Aperitivos
- Snacks
- Ensaladas
- Platos principales
- Guarniciones
- Sopas y caldos
- Postres
- Panadería
- Batidos y smoothies
- Comida saludable
- Comida vegetariana/vegana
- Comida sin gluten
- Tradicional
- Internacionales
- Dulces
- Eventos
